service: dynamic-demo-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

package:
  individually: true

plugins:
  #- serverless-webpack
  - serverless-offline
  - serverless-offline-local-authorizers-plugin
  - serverless-plugin-typescript

custom:
#  webpack:
#    webpackConfig: ./webpack.config.js
#    includeModules: false

  serverless-offline:
    httpPort: 3050
    lambdaPort: 3051
    noPrependStageInUrl: true
    noTimeout: true
    useChildProcesses: true

functions:
  getBalance:
    handler: src/handlers/getBalance.handler
    events:
      - http:
          path: wallet/balance
          method: GET
          authorizer:
            name: dynamicAuthorizer
            identitySource: method.request.header.Authorization
  sendTransaction:
    handler: src/handlers/sendTransaction.handler
    events:
      - http:
          path: wallet/transaction
          method: POST
          authorizer:
            name: dynamicAuthorizer
            identitySource: method.request.header.Authorization
  signMessage:
    handler: src/handlers/signMessage.handler
    events:
      - http:
          path: wallet/sign
          method: POST
          authorizer:
            name: dynamicAuthorizer
            identitySource: method.request.header.Authorization
  dynamicAuthorizer:
    handler: src/handlers/dynamicAuthorizer.handler

